server:
  port: 8080
  servlet:
    context-path: /blog/
spring:
  application:
    name: settings
  datasource:
    url: jdbc:mysql://49.235.229.8:3306/blog?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: zhulinzhong
    password: zhulinzhong
route:
  host: test.asd
  port: 8080
